    apiVersion: v1
    kind: Service
    metadata:
      name: python-app-service
    spec:
      type: LoadBalancer # This requests a Public IP from GCP
      selector:
        app: python-app
      ports:
      - protocol: TCP
        port: 80        # The port the Load Balancer listens on (External)
        targetPort: 8080 # The port the Pod listens on (Internal)