apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tal-test
  name: tal-test
spec:
  ports:
  - name: 8080-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: python-app
  type: ClusterIP
